// The retired selector's tests now exercise the authentication entry screen.
import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import AuthScreen from "../../src/components/AuthScreen.js";
import * as api from "../../src/api.js";
const user: api.AuthUser = { id: "alice", name: "Alice", email: "alice@example.com", role: "REQUESTER", isActive: true, mustChangePassword: false };
beforeEach(() => vi.restoreAllMocks());
describe("Authentication entry replaces Development Requester selection", () => {
    it("offers credentials, with no selector", () => { render(<AuthScreen user={null} onAuthenticated={vi.fn()} onLogout={vi.fn()}/>); expect(screen.getByLabelText("Email")).toBeInTheDocument(); expect(screen.getByLabelText("Password")).toHaveAttribute("type", "password"); expect(screen.queryByRole("combobox")).not.toBeInTheDocument(); });
    it("uses the identity returned by login", async () => { vi.spyOn(api, "login").mockResolvedValue({ user }); const done = vi.fn(); render(<AuthScreen user={null} onAuthenticated={done} onLogout={vi.fn()}/>); await userEvent.type(screen.getByLabelText("Email"), user.email); await userEvent.type(screen.getByLabelText("Password"), "Password123"); await userEvent.click(screen.getByRole("button", { name: "Login" })); expect(done).toHaveBeenCalledWith(user); });
    it("shows safe login failures", async () => { vi.spyOn(api, "login").mockRejectedValue(new Error("Invalid email or password.")); render(<AuthScreen user={null} onAuthenticated={vi.fn()} onLogout={vi.fn()}/>); await userEvent.type(screen.getByLabelText("Email"), user.email); await userEvent.type(screen.getByLabelText("Password"), "Wrong123"); await userEvent.click(screen.getByRole("button", { name: "Login" })); expect(await screen.findByRole("alert")).toHaveTextContent("Invalid email or password."); });
    it("validates password confirmation before submitting", async () => { const change = vi.spyOn(api, "changePassword"); render(<AuthScreen user={{ ...user, mustChangePassword: true }} onAuthenticated={vi.fn()} onLogout={vi.fn()}/>); await userEvent.type(screen.getByLabelText("Current Password"), "Initial123"); await userEvent.type(screen.getByLabelText("New Password"), "Changed123"); await userEvent.type(screen.getByLabelText("Confirm New Password"), "Different123"); await userEvent.click(screen.getByRole("button", { name: "Change Password" })); expect(await screen.findByRole("alert")).toHaveTextContent("must match"); expect(change).not.toHaveBeenCalled(); });
    it("finishes mandatory change using the server user", async () => { vi.spyOn(api, "changePassword").mockResolvedValue({}); vi.spyOn(api, "getCurrentUser").mockResolvedValue(user); const done = vi.fn(); render(<AuthScreen user={{ ...user, mustChangePassword: true }} onAuthenticated={done} onLogout={vi.fn()}/>); await userEvent.type(screen.getByLabelText("Current Password"), "Initial123"); await userEvent.type(screen.getByLabelText("New Password"), "Changed123"); await userEvent.type(screen.getByLabelText("Confirm New Password"), "Changed123"); await userEvent.click(screen.getByRole("button", { name: "Change Password" })); expect(done).toHaveBeenCalledWith(user); });
});
